# Generated by Django 5.0.3 on 2024-03-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentsid', models.BigIntegerField(max_length=10)),
                ('studentsfname', models.CharField(max_length=50, verbose_name='Firstname')),
                ('studentstname', models.CharField(max_length=50, verbose_name='Firstname')),
            ],
        ),
    ]
