# Generated by Django 5.0.3 on 2024-03-16 09:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_remove_students_studentsid'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='dateofjoinning',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date of admission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='phonenumber',
            field=models.CharField(default=0, max_length=10, verbose_name='lastname'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='studentstname',
            field=models.CharField(max_length=50, verbose_name='lastname'),
        ),
    ]
