# Generated by Django 5.0.3 on 2024-03-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_students_dateofjoinning_students_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
