# Generated by Django 5.0.3 on 2024-03-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_alter_students_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
