# Generated by Django 5.0.3 on 2024-03-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_students_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='phonenumber',
            field=models.CharField(max_length=10, verbose_name='phonenumber'),
        ),
    ]
