# Generated by Django 5.0.4 on 2024-04-14 11:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0009_students_date_of_birth_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
