# Generated by Django 5.0.4 on 2024-04-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0010_delete_customuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="student_profiles/"
                    ),
                ),
                ("phone_number", models.CharField(max_length=10)),
                ("date_of_joining", models.DateField()),
                ("date_of_birth", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="students",
        ),
    ]
