# Generated by Django 5.0.3 on 2024-04-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_student_delete_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(default='Adresss'),
        ),
        migrations.AddField(
            model_name='student',
            name='assignement',
            field=models.FileField(blank=True, null=True, upload_to='student_assignments/'),
        ),
        migrations.AddField(
            model_name='student',
            name='fees_Permonth',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='remaining_fees',
            field=models.FloatField(default=0.0),
        ),
    ]
